<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXoUavx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXoUavx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXoUavx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXoUavx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXoUavx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXoUavx',
    'container.build_id' => '9ff562bb',
    'container.build_time' => 1611173966,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXoUavx');
