<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY0iZxHS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY0iZxHS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY0iZxHS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY0iZxHS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY0iZxHS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y0iZxHS',
    'container.build_id' => '167e81bc',
    'container.build_time' => 1610448411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY0iZxHS');
