<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUCi8ja7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUCi8ja7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUCi8ja7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUCi8ja7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUCi8ja7\App_KernelDevDebugContainer([
    'container.build_hash' => 'UCi8ja7',
    'container.build_id' => '83ed6f5d',
    'container.build_time' => 1611237907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUCi8ja7');
