<?php

// This file was generated by running "composer dump-env test"

return array (
  'APP_ENV' => 'test',
  'APP_SECRET' => '$ecretf0rt3st',
  'DATABASE_URL' => 'mysql://testuser:localtesting@127.0.0.1:3306/restdb?serverVersion=13&charset=utf8',
  'KERNEL_CLASS' => 'App\\Kernel',
  'SYMFONY_DEPRECATIONS_HELPER' => '999999',
  'PANTHER_APP_ENV' => 'panther',
);
