security:
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_ADMIN ]
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        secured_area:
            pattern: ^/customer
            http_basic : ~
            security: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        # web version
        - { path: '^/customer', roles: [ IS_AUTHENTICATED_FULLY ] }





