security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_ADMIN: [ ROLE_ADMIN ]
        ROLE_MANAGER: [ ROLE_MANAGER ]
        ROLE_USER: [ ROLE_USER ]
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        secured_area:
            pattern: ^/customer
            http_basic : ~
            security: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        # web version
        - { path: '/customer', roles: [ IS_AUTHENTICATED_FULLY, ROLE_MANAGER ] }
        - { path: '/customer/{id}', roles: [ IS_AUTHENTICATED_FULLY, ROLE_MANAGER ] }
        - { path: '/customer/add', roles: [ IS_AUTHENTICATED_FULLY, ROLE_ADMIN ] }
        - { path: '/customer/update/{id}', roles: [ IS_AUTHENTICATED_FULLY, ROLE_ADMIN ] }
        - { path: '/customer/delete/{id}', roles: [ IS_AUTHENTICATED_FULLY, ROLE_ADMIN ] }





