<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ptpbC5\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ptpbC5/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7ptpbC5.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container7ptpbC5\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container7ptpbC5\App_KernelTestDebugContainer([
    'container.build_hash' => '7ptpbC5',
    'container.build_id' => 'dd6a2898',
    'container.build_time' => 1610535392,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ptpbC5');
