<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA6iax5t\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA6iax5t/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerA6iax5t.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerA6iax5t\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerA6iax5t\App_KernelTestDebugContainer([
    'container.build_hash' => 'A6iax5t',
    'container.build_id' => '526e60c2',
    'container.build_time' => 1614846882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA6iax5t');
