<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMfS1Asd\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMfS1Asd/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMfS1Asd.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMfS1Asd\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerMfS1Asd\App_KernelTestDebugContainer([
    'container.build_hash' => 'MfS1Asd',
    'container.build_id' => '045fa611',
    'container.build_time' => 1611230924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMfS1Asd');
