index:
    path: /
    controller: App\Controller\DefaultController::index


# config/routes.yaml

# the "app_main_number" route name is not important yet
add:
  path: /customer/add
  controller: App\Controller\CustomerController::add

get:
  path: /customer/{id}
  controller: App\Controller\CustomerController::get

getAll:
  path: /customer/
  controller: App\Controller\CustomerController::getAll

update:
  path: /customer/update/{id}
  controller: App\Controller\CustomerController::update

delete:
  path: /customer/delete/{id}
  controller: App\Controller\CustomerController::delete

app_logout:
  path: /logout
  methods: GET

indexadmin:
  path: /admin
  methods: GET
  controller: App\Controller\AdminController::index

admindashboard:
  path: /admin/dashboard
  methods: GET
  controller: App\Controller\AdminController::adminDashboard
