index:
    path: /
    controller: App\Controller\DefaultController::index
# config/routes.yaml
add:
  path: /customer/add
  controller: App\Controller\CustomerController::add

get:
  path: /customer/{id}
  controller: App\Controller\CustomerController::get

get_all:
  path: /customer/
  controller: App\Controller\CustomerController::getAll

update:
  path: /customer/update/{id}
  controller: App\Controller\CustomerController::update

delete:
  path: /customer/delete/{id}
  controller: App\Controller\CustomerController::delete

login:
  path:       /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: GET|POST

index_admin:
  path: /admin
  methods: GET
  controller: App\Controller\AdminController::index

admin_dashboard:
  path: /admin/dashboard
  methods: GET
  controller: App\Controller\AdminController::adminDashboard
